### ISSUE TITLE
Issue running pre-compiled jar

### ISSUE THREAD

**Issue by Skyfold** [CategoricalData/CQL#31]
When I run `java -jar cql.jar`, I get:
```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: catdata/ide/IDE has been compiled by a more recent version of the Java Runtime (class file version 54.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
```

`javac -version`
```
javac 12.0.1
```

`java -version`
```
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
```

Since the website says "Requires Java 12. Updated June 25, 2019 01:30 pm" I assume it should work with Java 12.

**Comment by wisnesky** [comment]
I believe that even though your javac reports version 12, your java reports version 8 (aka 1.8).  That could indicate a corrupt java install or path weirdness.

**Comment by Skyfold** [comment]
Sorry for the noise, its a local issue. The latest build works fine as long as you actually are running it with java 12...
